 name: Publish
 on:
   workflow_dispatch:
   push:
 jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
       contents: read
       packages: write
     steps:
     - name: "Checkout"
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
         fetch-tags: true
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2
     - name: Build with Gradle
       run: ./gradlew build
     - name: Upload build artifacts
       uses: actions/upload-artifact@v4
       with:
        name: Package
        path: build/lib
